## Introduction to Tensors 🚀

In [1]:
#import tensorflow 
import tensorflow as tf
tf.__version__

'2.9.1'

In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(2)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [3]:
# check the number of dimensions of a tensor
scalar.ndim

0

In [4]:
# Create vector
vector = tf.constant([2,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [5]:
# check the number of dimensions of a vector
vector.ndim

1

In [7]:
#Create a matrix (has more than 1 dim)
matrix = tf.constant([[2,3],
                     [4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [9]:
# Check the number of dimensions of a matrix
matrix.ndim

2

In [20]:
# Create another matrix
another_matrix = tf.constant([[1.,2.],
                             [3.,4.],
                             [5.,6.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [12]:
#Check the number of dimensions of another matrix
another_matrix.ndim

2

In [13]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[14,15,16],[17,18,19]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[14, 15, 16],
        [17, 18, 19]]])>

In [19]:
#Check dimensions of tensor
tensor.ndim


3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g wind speed and direction)
* Matrix: a 2-dim array of numbers
* Tensor: an n-dim array of numbers (when n can be any number, 0-dim tensor is a scalar, 1-dim tensor is vector)

### ✅ Creating tensors with 'tf.Variable' 

In [21]:
# Create the same tensor with tf.Variables() as above 
changeable_tensor = tf.Variable([10,7])
unchabgeable_tensor = tf.constant([10,7])
changeable_tensor, unchabgeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [22]:
# Let's try change one of the elements in out changeable_tensor and unchangeable_tensor
changeable_tensor[0] = 7
unchabgeable_tensor[0] = 7
changeable_tensor, unchabgeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [23]:
#How about we try .assighn()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [25]:
unchabgeable_tensor[0] = 7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment